// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wsybfcxtazqzxmvsktkl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndzeWJmY3h0YXpxenhtdnNrdGtsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4ODM4OTAsImV4cCI6MjA1ODQ1OTg5MH0.OPnB68LIvWvG6uzSUQkrMJ-_HvKXWXAp9pj-CryjCTc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);